ImageMagick is used for handling images and video thumbnail generation
I met error during deploying latest from GIT:
WARNING: Failed to scan JAR
[jndi:/localhost/imeji/WEB-INF/lib/jena-arq-2.10.1.jar] from WEB-INF/lib
java.util.zip.ZipException: error in opening zip file